package com.cybelinx.platform.shared;

/**
 * Port of {@code @cybelinx/shared} ErrorCode. Canonical error codes for the control plane API.
 */
public enum ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    TENANT_NOT_FOUND,
    TENANT_INACTIVE,
    TENANT_ACCESS_DENIED,
    TENANT_CODE_TAKEN,
    TENANT_STATUS_TRANSITION_INVALID,
    TENANT_PRODUCT_NOT_FOUND,
    TENANT_PRODUCT_ALREADY_ASSIGNED,
    TENANT_PRODUCT_STATUS_TRANSITION_INVALID,
    PRODUCT_NOT_FOUND,
    PRODUCT_NOT_ACTIVE,
    PRODUCT_CODE_TAKEN,
    PRODUCT_STATUS_TRANSITION_INVALID,
    PRODUCT_NOT_ENTITLED,
    PRODUCT_VERSION_NOT_FOUND,
    PRODUCT_VERSION_TAKEN,
    PLAN_NOT_FOUND,
    PLAN_NOT_ACTIVE,
    PLAN_CODE_TAKEN,
    PLAN_STATUS_TRANSITION_INVALID,
    ENTITLEMENT_NOT_FOUND,
    ENTITLEMENT_KEY_TAKEN,
    ENTITLEMENT_STATUS_TRANSITION_INVALID,
    REGION_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    RESOURCE_NOT_READY,
    TENANT_RESOURCE_NOT_FOUND,
    TENANT_RESOURCE_ALREADY_REGISTERED,
    EXTERNAL_ID_NOT_FOUND,
    EXTERNAL_ID_ALREADY_MAPPED,
    PROVISIONING_FAILED,
    PROVISIONING_JOB_NOT_FOUND,
    PROVISIONING_JOB_NOT_CLAIMABLE,
    INVALID_TENANT_CONTEXT,
    USAGE_QUOTA_EXCEEDED,
    INTERNAL_ERROR;

    /** HTTP status used when the {@link ApiError} does not declare one explicitly. */
    public static int defaultHttpStatus(ErrorCode code) {
        return switch (code) {
            case UNAUTHORIZED -> 401;
            case FORBIDDEN, PRODUCT_NOT_ENTITLED, INVALID_TENANT_CONTEXT -> 403;
            case VALIDATION_ERROR -> 400;
            case TENANT_NOT_FOUND, PRODUCT_NOT_FOUND, PRODUCT_VERSION_NOT_FOUND,
                    PLAN_NOT_FOUND, ENTITLEMENT_NOT_FOUND, TENANT_PRODUCT_NOT_FOUND,
                    REGION_NOT_FOUND, RESOURCE_NOT_FOUND, TENANT_RESOURCE_NOT_FOUND,
                    EXTERNAL_ID_NOT_FOUND,
                    PROVISIONING_JOB_NOT_FOUND -> 404;
            case TENANT_INACTIVE, TENANT_CODE_TAKEN, TENANT_STATUS_TRANSITION_INVALID,
                    TENANT_PRODUCT_ALREADY_ASSIGNED, TENANT_PRODUCT_STATUS_TRANSITION_INVALID,
                    PRODUCT_NOT_ACTIVE, PRODUCT_CODE_TAKEN, PRODUCT_STATUS_TRANSITION_INVALID,
                    PRODUCT_VERSION_TAKEN, PLAN_NOT_ACTIVE,
                    PLAN_CODE_TAKEN, PLAN_STATUS_TRANSITION_INVALID,
                    ENTITLEMENT_KEY_TAKEN, ENTITLEMENT_STATUS_TRANSITION_INVALID,
                    TENANT_RESOURCE_ALREADY_REGISTERED, EXTERNAL_ID_ALREADY_MAPPED,
                    PROVISIONING_JOB_NOT_CLAIMABLE -> 409;
            case USAGE_QUOTA_EXCEEDED -> 429;
            case RESOURCE_NOT_READY -> 503;
            case TENANT_ACCESS_DENIED -> 403;
            case PROVISIONING_FAILED, INTERNAL_ERROR -> 500;
        };
    }
}